spring:
  datasource:
##    url: jdbc:h2:~/jpashop
##    url: jdbc:h2:mem:jpashop
##    url: jdbc:h2:tcp//localhost:8080/./jpashop
    url: jdbc:postgresql://localhost:5432/postgres
    username: digilog
    password: bistel01
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#  h2:
#    console:
#      enabled=true
#      path=/h2-console

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
